# Generated by Django 5.0.6 on 2024-06-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_remove_userprofile_profile_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile_images"),
        ),
    ]
