# Generated by Django 5.0.6 on 2024-05-26 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="encoding",
            field=models.JSONField(default=dict),
        ),
    ]
